cncjs/cncjs

package.json
src/app/api/api.macros.js
src/app/api/api.users.js

Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …

Update uuid to version 3.0.0

---

src/app/controllers/Grbl/GrblController.js
src/app/controllers/Marlin/MarlinController.js
src/app/controllers/Smoothie/SmoothieController.js
src/app/controllers/TinyG/TinyGController.js

Pausing the workflow on M2 and M30 is unnecessary and inappropriate.  Those commands are only used at the end of a GCode program, where there is no reason to require user action to return to the idle state.
Historically, back when CNC machines used punched paper tape, it was common to splice together multiple program tapes, either to set up a sequence of related programs, or to repeat one program by splicing the end of the tape to the beginning.  In that old use case, M30 and M2 were needed to mark the end of the tape or the boundary between programs, to prevent the tape reader from reading too far.  Now that GCode programs are stored in computer files, the tape model is no longer used, so M2 and M30 are essentially equivalent to "end of file".  Pausing with the possibility of resuming is …

M2 and M30 do not pause workflow

---

src/web/store/index.js

This PR fixed a bug (#416) that configured axes was not saved after browser refresh.

Fix a bug that Axes widget does not remember configured axes (#416)

---

src/app/controllers/Marlin/MarlinController.js

As described in #312, Marlin controllers can sometimes hang at startup until you manually send some Gcode (e.g. ` G0 X0`, at which point all queued commands run). This PR implements @cheton's recommended fix in [his comment](https://github.com/cncjs/cncjs/issues/312#issuecomment-401504386).

Fix for Marlin controller first-move bug (issue #312)

---

src/web/containers/Workspace/PrimaryWidgets.jsx
src/web/containers/Workspace/SecondaryWidgets.jsx
src/web/widgets/Axes/DisplayPanel.jsx

Fix an issue that dropdown menu gets clipped by container with overflow:hidden property (#445)

---

src/app/controllers/Marlin/MarlinController.js

This is the bug @cheton discussed in https://github.com/cncjs/cncjs/issues/454#issuecomment-484427057
Closes #454

Fix for the lastQueryTime Marlin bug

---

src/server/controllers/Marlin/MarlinController.js

Handle both initial Marlin power-on and connection close/re-open.
Marlin issues a 'start' line only on initial power-up.   If the serial connection to Marlin was closed and then re-opened, CNCjs would set it's ready variable to false and it would never go back to true because opening the connection would not result in a 'start' line.
The solution is use the 'firmware' response to indicate readiness, issuing an 'M115' firmware report request both on connection open and on receipt of 'start'.
This fix resulted in reliable position reports from Marlin in every scenario that I tested.

Improve Marlin startup synchronization (#312)

---

src/server/controllers/Marlin/MarlinController.js

PR #464 introduced a regression that caused a bug similar to #312, where Marlin would be unresponsive until a command was manually entered in the console (e.g. `G0 X0`). This PR includes the fix @MitchBradley suggested in [this comment](https://github.com/cncjs/cncjs/pull/464#issuecomment-489476430).
I've verified on my Marlin board that this fix solves the issue (UltiMachine Rambo running [github.comAllted/Marlin](https://github.com/Allted/Marlin/tree/MPCNC_Rambo_T8_16T_LCD_DualEndstop))

Fix Marlin startup regression from #464

---

src/app/components/Space/Space.jsx
src/app/i18n/cs/resource.json
src/app/i18n/de/resource.json
src/app/i18n/en/resource.json
src/app/i18n/es/resource.json
src/app/i18n/fr/resource.json
src/app/i18n/hu/resource.json
src/app/i18n/it/resource.json
src/app/i18n/ja/resource.json
src/app/i18n/nl/resource.json
src/app/i18n/pt-br/resource.json
src/app/i18n/ru/resource.json
src/app/i18n/tr/resource.json
src/app/i18n/zh-cn/resource.json
src/app/i18n/zh-tw/resource.json
src/app/widgets/Webcam/Settings.jsx
src/app/widgets/Webcam/Webcam.jsx

Assuming `window.location.hostname` is `192.168.1.1`:
* `http://0.0.0.0:8000/` will be changed to `http://192.168.1.1:8000/`
* `https://0.0.0.0:8000/` will be changed to `https://192.168.1.1:8000/`
* `//0.0.0.0:8000/` will be changed to `//192.168.1.1:8000/`

Add meta address support for specifying the hostname of an IP camera URL (#471)

---

src/app/widgets/Axes/index.jsx

Marlin always reports positions in mm, regardless of whether it is in inch (G20) or mm (G21) mode.

Fixed issue #318 - Marlin Inch Mode still shows MM in DRO

---

src/app/widgets/Axes/index.jsx

Commit 86b9827 broke master as can be seen here https://travis-ci.org/cncjs/cncjs/builds/550912101 and the reason seems to be a missing space character. Which in turn causes a lint error.
Interestingly no such error can be seen in the logging output of the failed build, which is weird.

Fix missing space error

---

src/server/controllers/Smoothie/SmoothieLineParserResultParserState.js

Smoothieware edge returns a State string prefixed with hardcoded `GC:`

Allow for optional State prefix of GC

---

src/app/widgets/Visualizer/index.jsx

Fixes #614 by showing notifications on both views.  Also removes footer/toolbar from the listing view where it is not used and also obscures the bottom part of the listing.

Also show toast notifications on g-code listing view of Visualizer (fixes #614)

---

package.json
src/app/containers/Workspace/Workspace.jsx
src/app/containers/Workspace/modals/FeederPaused.jsx
src/app/containers/Workspace/modals/FeederWait.jsx
src/package.json
src/server/controllers/Grbl/GrblController.js
src/server/controllers/Marlin/MarlinController.js
src/server/controllers/Smoothie/SmoothieController.js
src/server/controllers/TinyG/TinyGController.js

Capture any line comment (everything after a semicolon) on an M0, M1
or M6 command and display is as part of the pause dialog in the UI.
Fixes #467.

Propagate line comments in GRBL M0/M1/M6 commands to UI dialog

---

package.json

Pre-push was set to `eslint:debug` but defined script is using `eslint-debug`

fix: fix wrong `pre-push` hook in `package.json`

---

src/server/controllers/Grbl/GrblRunner.js
test/grbl.js

This is a fix for https://github.com/cncjs/cncjs/issues/596 
Soft limit alarms aren't handled by the `GrblLineParserResultStatus` module, because they don't match the [`<State|...>` regex](https://github.com/cncjs/cncjs/blob/master/src/server/controllers/Grbl/GrblLineParserResultStatus.js#L19))
This causes cncjs to be in a half-broken idle state, where there is no visible indication that something's gone wrong. This is especially true if the UI was closed during the alarm event (or reloaded after), so that the alarm message will not appear in the serial console.

Grbl: Fix for missing alarm state for non `<Alarm|...>` lines (like soft limits)

---

src/app/widgets/Visualizer/Notifications.js
src/app/widgets/Visualizer/index.jsx

feat: display the G-code line of certain M commands (e.g. M0/M1/M6/...) in the toast notification

---

src/server/controllers/Marlin/MarlinLineParserResultTemperature.js
test/marlin.js

Related to https://github.com/cncjs/cncjs/issues/759 (@rflulling)
This PR adds support for Marlin 2.0 temperature report format:
```
ok T0:27.58 /0.00 B:28.27 /0.00 T0:27.58 /0.00 T1:27.37 /0.00 @:0 B@:0 @0:0 @1:0
T0:27.72 /0.00 B:28.38 /0.00 T0:27.72 /0.00 T1:27.28 /0.00 @:0 B@:0 @0:0 @1:0
wait
wait
T0:27.66 /0.00 B:28.30 /0.00 T0:27.66 /0.00 T1:27.28 /0.00 @:0 B@:0 @0:0 @1:0
```

feat: add support for new Marlin 2.0 temperature report format

---

.circleci/config.yml

I considered attempting to restrict this to `master` branch builds only, but it appears that `$CIRCLE_BRANCH` is empty during the `deploy-tag` job. Looks like if it's a tag build, then `$CIRCLE_TAG` is populated instead. I inspected [this run](https://app.circleci.com/pipelines/github/cncjs/cncjs/235/workflows/9e21b68c-04cc-4498-a47a-c33fb712a251/jobs/403).
Tag builds should be safe to tag as `latest`, I think.
Resolves https://github.com/cncjs/cncjs/issues/741

Push latest tag on tag builds

---

.circleci/config.yml

First attempt in https://github.com/cncjs/cncjs/pull/784 was [broken](https://app.circleci.com/pipelines/github/cncjs/cncjs/237/workflows/8ff05004-b348-4103-a148-47c91f099bc6/jobs/405):
```
0ac3c0fe: Preparing 
57fd6d7d: Preparing 
0ef44274: Preparing 
2ef10e9a: Preparing 
v1.9.28: digest: sha256:0ab6d82f48cfc3bfe6faf05dcef435e7a052910679bdb0f534267d4d45b3ca0b size: 1372
Error response from daemon: No such image: v1.9.28:latest
Exited with code exit status 1
CircleCI received exit code 1
```
This should fix the `docker tag` syntax.

Fix Docker tag syntax

---

appveyor.yml
src/app/i18n/cs/resource.json
src/app/i18n/de/resource.json
src/app/i18n/en/resource.json
src/app/i18n/es/resource.json
src/app/i18n/fr/resource.json
src/app/i18n/hu/resource.json
src/app/i18n/it/resource.json
src/app/i18n/ja/resource.json
src/app/i18n/nb/resource.json
src/app/i18n/nl/resource.json
src/app/i18n/pt-br/resource.json
src/app/i18n/pt-pt/resource.json
src/app/i18n/ru/resource.json
src/app/i18n/tr/resource.json
src/app/i18n/zh-cn/resource.json
src/app/i18n/zh-tw/resource.json
src/app/widgets/Webcam/Settings.jsx
src/app/widgets/Webcam/Webcam.jsx
src/app/widgets/Webcam/constants.js
src/app/widgets/Webcam/index.jsx

A simple update to the webcam widget that allows the use of the HTML5 `<video/>` tag for suitable remote streams.
It means less faffing about and expensive conversions for those of us that have, say,  h264-capable webcams  attached to a pi. We may use for example [https://github.com/soyersoyer/fmp4streamer](https://github.com/soyersoyer/fmp4streamer)  
If your stream URL ends with ".mp4" it will simply switch out the `<Image/>` tag for `<video/>`

html5-webcam: feat: Update Webcam widget to allow streaming h264(mp4)

---

src/server/controllers/Grbl/GrblController.js
src/server/controllers/Marlin/MarlinController.js
src/server/controllers/Smoothie/SmoothieController.js
src/server/controllers/TinyG/TinyGController.js

While debugging programs, it's confusing for the g-code list view to show a different number of lines than the g-code widget.  This comes from the fact that the load routines remove blank lines and add a dwell at the end of the program.
This PR syncs those up by returning the as-loaded gcode in the gcode:load event.

Return as-loaded gcode in gcode:load event

---

src/app/i18n/cs/resource.json
src/app/i18n/de/resource.json
src/app/i18n/en/resource.json
src/app/i18n/es/resource.json
src/app/i18n/fr/resource.json
src/app/i18n/hu/resource.json
src/app/i18n/it/resource.json
src/app/i18n/ja/resource.json
src/app/i18n/nb/resource.json
src/app/i18n/nl/resource.json
src/app/i18n/pt-br/resource.json
src/app/i18n/pt-pt/resource.json
src/app/i18n/ru/resource.json
src/app/i18n/tr/resource.json
src/app/i18n/zh-cn/resource.json
src/app/i18n/zh-tw/resource.json
src/app/store/defaultState.js
src/app/widgets/Connection/Connection.jsx
src/app/widgets/Connection/index.jsx
src/server/controllers/Grbl/GrblController.js
src/server/controllers/Marlin/MarlinController.js
src/server/controllers/Smoothie/SmoothieController.js
src/server/controllers/TinyG/TinyGController.js
src/server/lib/SerialConnection.js
src/server/services/cncengine/CNCEngine.js

This PR adds two options that allows users to set or clear DTR and RTS line status when the serial connection is opened. The process is intended for the Arduino Due board, but may also work for certain other boards.
https://user-images.githubusercontent.com/447801/228857357-d00a2b48-89ff-4978-8a62-380a51f814b7.mp4
https://playground.arduino.cc/Main/DisablingAutoResetOnSerialConnection/
https://arduino.stackexchange.com/questions/38012/major-difference-between-dtr-signal-and-rts-signal
https://www.geeksforgeeks.org/difference-between-rts-cts-and-dtr-dsr-flow-control/
https://github.com/serialport/node-serialport/blob/6f453b60ac22909334dd128832d7b5eceecbbca6/examples/reset.js
https://forum.arduino.cc/t/disable-auto-reset-by-serial-connection/28248/4 …

feat: add functionality to set DTR/RTS line status on serial port open

---

entrypoint

Applies the fix from https://github.com/cncjs/cncjs/pull/803 to the Docker entrypoint script so that the Docker images can run properly.
This is not fully functional yet: when accessing the app from the browser an error displays and the container logs out:
```
2023-05-17T03:29:37.666Z - info init Loading configuration from "/root/.cncrc"
(node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
2023-05-17T03:29:37.725Z - info init Starting the server at http://172.17.0.2:8000
Error: Failed to lookup view "index.hbs" in views directories "/opt/cncjs/app" or "/opt/cncjs/server/views"
at Function.render (/opt/cncjs/node_modules/express/lib/application.js:580:17)
at …
```

fix: @babel/polyfill not found in Docker container

---

src/server/controllers/Marlin/MarlinLineParserResultTemperature.js
test/marlin.js

This PR adds support for parsing temperature data associated with the heated chamber, cooler, and other temperature states, specifically for Marlin 2.x.
For more information regarding this issue, please refer to https://github.com/cncjs/cncjs/issues/581#issuecomment-1611526566

feat(Marlin): add support for parsing temperature data for heated chamber, cooler, and other temperature states

---

src/server/controllers/Grbl/GrblController.js
src/server/lib/Feeder.js

Grbl v1.1 controllers support additional Extended Ascii Realtime
Comands:
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#extended-ascii-realtime-command-descriptions
The jogCancel command is sent as the character 0x85, and is useful
for implementing Grbl v1.1 jogging:
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Jogging
The 0x85 character cannot be sent over socket.io as an argument to
the gcode command because it does not form a valid UTF8 byte
sequence.  Add a jogCancel command that causes CNCjs to send
the 0x85 character to the Grbl controller.

Add a Grbl jogCancel command

---

src/app/lib/combokeys.js

The wiki page has been updated as followed:
https://github.com/cncjs/cncjs/wiki/User-Guide#keyboard-shortcuts
* <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>command</kbd> + <kbd>]</kbd> or <kbd>f</kbd> - Jog Forward<br>
* <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>command</kbd> + <kbd>[</kbd> or <kbd>k</kbd> - Jog Backward<br>
bug_fix
___
- Resolved a conflict in shortcut key assignments within the `Combokeys` library.
- Updated the key combination for the Jog Backward command to prevent conflicts.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>combokeys.js</strong><dd><code>Resolve conflicting shortcut key assignments in Combokeys</code></dd></summary>
<hr> …

fix: resolve conflicting shortcut key assignments in `Combokeys`

---

src/server/controllers/TinyG/TinyGController.js

https://github.com/synthetos/g2/wiki/Feedhold,-Resume,-and-Other-Simple-Commands#jogging-using-feedhold-and-queue-flush
* Send a `!` to stop movement immediately
* Send a `%` to flush remaining moves from planner buffer
enhancement
___
- Introduced a new `jogCancel` command in the TinyGController to enhance jogging control.
- The `jogCancel` command stops movement immediately using feedhold and flushes the queue to clear remaining moves.
- This implementation follows the guidelines from the g2 wiki on jogging using feedhold and queue flush.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>TinyGController.js</strong><dd><code>Add `jogCancel` command to …

feat(`g2`, `tinyg`): add `jogCancel` command to cancel jogging using feedhold and queue flush

---

src/server/controllers/Grbl/GrblController.js

enhancement
___
- Enhanced the Grbl controller to support UART communication without resetting the connection upon opening.
- Added logic to handle scenarios where a startup message is not received, ensuring the controller is marked as ready and initialized.
- Introduced a throttled `queryActivity` function to periodically send status queries when the connection is open.
- Improved the initialization process by checking and setting `ready` and `initialized` flags appropriately.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>GrblController.js</strong><dd><code>Enhance UART communication handling and initialization logic</code></dd></summary>
<hr> …

feat(Grbl): support UART communication without resetting the connection upon opening

---

src/app/containers/Login/Login.jsx
src/app/index.jsx

Fix a regression introduced in PR #877 
___
- Fixed a regression where `api.getState` was only accessible with an authenticated session.
- Enhanced the login process by initializing Google Analytics if anonymous usage data collection is allowed.
- Refactored the application startup to initialize Google Analytics after successful authentication.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Login.jsx</strong><dd><code>Enhance login with Google Analytics initialization</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/app/containers/Login/Login.jsx
<li>Added import for <code>GoogleAnalytics4</code> and <code>api</code>.<br> <li> …

fix: resolve a regression where `api.getState` is only accessible only with an authenticated session
